spring:
  application:
    name: adg-rule
  profiles:
    active: prod #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      - https://easylist-downloads.adblockplus.org/easylist.txt
      - https://easylist-downloads.adblockplus.org/easylistchina.txt
      - https://easylist-downloads.adblockplus.org/easyprivacy.txt
      - https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt
      - https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt
      - https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt
      - https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
      - https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-ublock.txt
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - "mylist.txt"
  output:
    path: rule #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      # all.txt: #输出文件名
      #   - DOMAIN #域名规则，仅完整域名
      #   - REGEX #正则规则，包含正则的域名规则，AdGH支持
      #   - MODIFY #修饰规则，添加了一些修饰符号的规则，AdG支持
      #   - HOSTS #Hosts规则
      rules.txt:
        - DOMAIN
        - REGEX
        - HOSTS
      # hosts.txt:
      #   - HOSTS
      # regex.txt:
      #   - REGEX
      # domain.txt:
      #   - DOMAIN
      # modify.txt:
      #   - MODIFY
