name: Build Go Exec Files
on:
  push: # 每次 push 的时候触发
    paths-ignore:
      - "README.md"
      - "README_en.md"
    branches: [main]
  schedule:
    - cron: 0 8 * * 3

env:
  TZ: Asia/Shanghai
  CGO_ENABLED: 0
  GOOS: linux
  GOARCH: amd64

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest go version
        id: version
        run: |
          echo ::set-output name=go_version::$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g')
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.version.outputs.go_version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Build sing-box
        if: success()
        run: go install -v -tags with_quic,with_grpc github.com/sagernet/sing-box/cmd/sing-box@latest # 这 3 条是交叉编译 Go 的指令，酌情修改。

      - name: Move file
        if: success()
        run: mv ~/bin/sing-box ./sing-box-server

      - name: Cache xcaddy
        if: success()
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Build caddy
        if: success()
        run: ~/bin/xcaddy build --with github.com/caddyserver/forwardproxy@caddy2=github.com/klzgrad/forwardproxy@naive --with github.com/mholt/caddy-l4 --with github.com/mastercactapus/caddy2-proxyprotocol

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          tag_name: weekly
          files: |
            caddy
            sing-box-server
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
